[project]
name = "llm-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Udara Sandesha", email = "udarasandesha@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.0",
    "openai>=2.53.0",
    "python-dotenv>=1.2.2",
    "requests>=2.32.0",
]

[project.scripts]
llm-playground = "llm_playground:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
